# Generated by Django 5.2.10 on 2026-02-01 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("date", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FOOD", "Food"),
                            ("RENT", "Rent"),
                            ("TRANSPORT", "Transport"),
                            ("ENTERTAINMENT", "Entertainment"),
                            ("UTILITIES", "Utilities"),
                            ("HEALTH", "Health"),
                            ("SHOPPING", "Shopping"),
                            ("EDUCATION", "Education"),
                            ("OTHER", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="transaction_user_id_8af7f1_idx"
                    ),
                    models.Index(
                        fields=["user", "category", "date"],
                        name="transaction_user_id_afbf84_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="transaction_amount_gt_0",
                    )
                ],
            },
        ),
    ]
