# Generated by Django 5.2.10 on 2026-02-03 08:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="transaction",
            name="transaction_user_id_10b37a_idx",
        ),
        migrations.AddField(
            model_name="transaction",
            name="txn_type",
            field=models.CharField(
                choices=[("INCOME", "Income"), ("EXPENSE", "Expense")],
                default="income",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "txn_type", "date"],
                name="transaction_user_id_fef26c_idx",
            ),
        ),
    ]
