# Generated by Django 5.2.10 on 2026-02-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transactions",
            "0002_remove_transaction_transaction_user_id_10b37a_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="txn_type",
            field=models.CharField(
                choices=[("INCOME", "Income"), ("EXPENSE", "Expense")],
                default="EXPENSE",
                max_length=10,
            ),
        ),
    ]
